version: '3.4'

services:
  springboot-demo:
    image: springboot-demo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      APP_ENV: dev
    volumes: 
      - ".:/app"
    depends_on:
      - "db"
    networks:
      - springboot-network
      
  db:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - springboot-network
      
networks:
  springboot-network:
    driver: bridge
    
volumes:
  db: