version: '3.4'

services:
  springboot-starter:
    image: silverwebs/springboot-starter
    build:
      context: .
      dockerfile: docker/${APP_ENV}.dockerfile
    ports:
      - 8080:8080
    environment:
      APP_ENV: ${APP_ENV}
    volumes: 
      - ".:/app"
    depends_on:
      - "db"
    networks:
      - springboot-network
      
  db:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: conference_app
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - springboot-network
      
networks:
  springboot-network:
    driver: bridge
    
volumes:
  db: